import { Router } from "express";
import { router as health } from "./modules/health/router.js";
import { router as me } from "./modules/me/router.js";
import { router as ops } from "./modules/ops/router.js";
import auth from "./modules/auth/router.js";
import { router as webhooks } from "./modules/webhooks/router.js";
import { router as pub } from "./modules/public/router.js";
import { router as tenants } from "./modules/tenants/router.js";
import { router as staff } from "./modules/staff/router.js";
import { router as serviceCategories } from "./modules/service-categories/router.js";
import { router as services } from "./modules/services/router.js";
import { router as appointments } from "./modules/appointments/router.js";
import { router as timers } from "./modules/timers/router.js";
import { router as waitlist } from "./modules/waitlist/router.js";
import { router as clients } from "./modules/clients/router.js";
import { router as clientsGlobal } from "./modules/clients-global/router.js";
import { router as inventory } from "./modules/inventory/router.js";
import { router as pos } from "./modules/pos/router.js";
import { router as payments } from "./modules/payments/router.js";
import { router as connect } from "./modules/connect/router.js";
import { router as subscriptions } from "./modules/subscriptions/router.js";
import { router as forms } from "./modules/forms/router.js";
import { router as uploads } from "./modules/uploads/router.js";
import { router as marketing } from "./modules/marketing/router.js";
import { router as reports } from "./modules/reports/router.js";
import { router as settings } from "./modules/settings/router.js";
import { router as integrations } from "./modules/integrations/router.js";

const routes: import("express").Router = Router();

routes.use("/health", health);
routes.use("/auth", auth);
routes.use("/me", me);
routes.use("/ops", ops);
routes.use("/webhooks", webhooks);
routes.use("/public", pub);
routes.use("/tenants", tenants);
routes.use("/staff", staff);
routes.use("/service-categories", serviceCategories);
routes.use("/services", services);
routes.use("/appointments", appointments);
routes.use("/timers", timers);
routes.use("/waitlist", waitlist);
routes.use("/clients", clients);
routes.use("/clients-global", clientsGlobal);
routes.use("/inventory", inventory);
routes.use("/pos", pos);
routes.use("/payments", payments);
routes.use("/connect", connect);
routes.use("/subscriptions", subscriptions);
routes.use("/forms", forms);
routes.use("/uploads", uploads);
routes.use("/marketing", marketing);
routes.use("/reports", reports);
routes.use("/settings", settings);
routes.use("/integrations", integrations);

export default routes;
